name: Build NVTOP Application

on:
  workflow_dispatch:
    inputs:
      nightly-build:
        description: "Nightly build"
        type: boolean
        required: true
        default: false
  push:
    tags:
      - "*"

jobs:
  build:
    name: Build App
    strategy:
      matrix:
        os: [ubuntu-24.04, ubuntu-24.04-arm, ubuntu-22.04, ubuntu-22.04-arm]
        include:
          - os: ubuntu-24.04
            codename: "noble"
          - os: ubuntu-24.04-arm
            codename: "noble"
          - os: ubuntu-22.04
            codename: "jammy"
          - os: ubuntu-22.04-arm
            codename: "jammy"
    runs-on: ${{ matrix.os }}
    if: ${{ github.event_name == 'push' || github.event.inputs.nightly-build == 'false' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install libraries
        run: |
          sudo apt-get update
          sudo apt-get install libncurses5-dev libncursesw5-dev libdrm-dev
          sudo apt-get install libfuse2

      - name: Install build tools
        run: |
          sudo apt-get install -y dh-make devscripts build-essential

      - name: Build and make release
        run: |
          bash ${{ github.workspace }}/release.sh

      - name: Upload workflow artifacts
        uses: actions/upload-artifact@v4
        with:
          name: nvtop-${{ matrix.codename }}
          path: |
            ${{ github.workspace }}/release/nvtop_*.deb
            ${{ github.workspace }}/release/nvtop-*.rpm
            ${{ github.workspace }}/release/nvtop-*.AppImage

      - name: Display debian folder
        run: |
          echo "Debian folder content:"
          ls -la ${{ github.workspace }}/debian/
          echo "Release folder content:"
          ls -la ${{ github.workspace }}/release/
          echo "Control file content:"
          cat ${{ github.workspace }}/debian/control
          echo "Changelog file content:"
          cat ${{ github.workspace }}/debian/changelog

      - name: Publish PPA package
        uses: yuezk/publish-ppa-package@main
        if: matrix.codename == 'jammy' && github.event_name != 'workflow_dispatch'
        with:
          tarball: ${{ github.workspace }}/release/nvtop-*.tar.gz
          debian_dir: ${{ github.workspace }}/debian/
          repository: "quentiumyt/nvtop"
          deb_email: "pro@quentium.fr"
          deb_fullname: "Quentin Lienhardt"
          gpg_private_key: ${{ secrets.PPA_GPG_PRIVATE_KEY }}
          gpg_passphrase: ${{ secrets.PPA_GPG_PASSPHRASE }}
          series: "noble jammy"
          new_version_template: "{VERSION}-{REVISION}+{SERIES}"
          keep_changelog: true

  nightly-build:
    name: Build Nightly App
    runs-on: ubuntu-22.04, ubuntu-22.04-arm
    if: ${{ github.event.inputs.nightly-build == 'true' }}
    steps:
      - name: Checkout
        uses: actions/checkout@main
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Install libraries
        run: |
          sudo apt-get update
          sudo apt-get install libncurses5-dev libncursesw5-dev libdrm-dev libsystemd-dev libudev-dev
          sudo apt-get install libfuse2

      - name: Install build tools
        run: |
          sudo apt-get install -y dh-make devscripts build-essential lintian

      - name: Build and make nightly release
        run: |
          bash ${{ github.workspace }}/release.sh nightly

      - name: Upload workflow artifacts
        uses: actions/upload-artifact@v4
        with:
          name: nvtop-nightly
          path: |
            ${{ github.workspace }}/release/nvtop-nightly_*.deb
            ${{ github.workspace }}/release/nvtop-nightly-*.rpm
            ${{ github.workspace }}/release/nvtop-nightly-*.AppImage

      - name: Get commit count
        id: commit_count
        run: |
          LAST_TAG=$(git describe --tags --abbrev=0 || echo "HEAD")
          COMMITS=$(git rev-list --count $LAST_TAG..HEAD)
          echo "last_tag=$LAST_TAG" >> $GITHUB_ENV
          echo "commit_count=$COMMITS" >> $GITHUB_ENV

      - name: Update debian files
        run: |
          sed -i "s/${{ env.last_tag }}-/${{ env.last_tag }}+${{ env.commit_count }}-/g" ${{ github.workspace }}/debian/changelog
          sed -i "s/^nvtop/nvtop-nightly/g" ${{ github.workspace }}/debian/changelog
          sed -i "s/ nvtop$/ nvtop-nightly/g" ${{ github.workspace }}/debian/control
          sed -i "s/Architecture: all/Architecture: all\nProvides: nvtop/g" ${{ github.workspace }}/debian/control
          sed -i "s/Architecture: all/Architecture: all\nConflicts: nvtop/g" ${{ github.workspace }}/debian/control
          sed -i "s/Architecture: all/Architecture: all\nReplaces: nvtop/g" ${{ github.workspace }}/debian/control
          REVISION=$(grep -oP '\-\d+' debian/changelog | head -n 1 | cut -d '-' -f 2)
          echo "revision=$REVISION" >> $GITHUB_ENV

      - name: Display debian folder
        run: |
          echo "Debian folder content:"
          ls -la ${{ github.workspace }}/debian/
          echo "Release folder content:"
          ls -la ${{ github.workspace }}/release/
          echo "Control file content:"
          cat ${{ github.workspace }}/debian/control
          echo "Changelog file content:"
          cat ${{ github.workspace }}/debian/changelog

      - name: Publish PPA package
        uses: yuezk/publish-ppa-package@main
        with:
          tarball: ${{ github.workspace }}/release/nvtop-nightly-*.tar.gz
          debian_dir: ${{ github.workspace }}/debian/
          repository: "quentiumyt/nvtop"
          deb_email: "pro@quentium.fr"
          deb_fullname: "Quentin Lienhardt"
          gpg_private_key: ${{ secrets.PPA_GPG_PRIVATE_KEY }}
          gpg_passphrase: ${{ secrets.PPA_GPG_PASSPHRASE }}
          series: "noble jammy"
          revision: ${{ env.revision }}
          new_version_template: "{VERSION}-{REVISION}+{SERIES}"
          keep_changelog: true
